# -*- coding: utf-8 -*-
"""Cópia de WebScraping_Wikipedia.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1RhbJ32pP7ZZtzqM4ArXKzIBJTDwbaaJ7

A obtenção de dados disponíveis na web é uma prática importante para um profissional que lide com aplicações de Processamento de Linguagem Natural.
Neste notebook, um exemplo de exploração dados disponibilizados em páginas web.

No caso será realizada a captura do conteúdo de uma página da Wikipedia. serão utilizadas as bibliotecas [Requests](https://pypi.org/project/requests/) e [Beautiful Soap](https://beautiful-soup-4.readthedocs.io/en/latest/).
"""

from bs4 import BeautifulSoup
import requests as r

url='https://mapa.apps.tcu.gov.br/noticia/NOTICIA_CLIPPING_70009177'
response = r.get(url)

wget ()

soup=BeautifulSoup(response.text, 'html.parser')

print(soup.prettify())

print(soup.title)
print(soup.title.string)
print(soup.a.string)
print(soup.b.string)

for x in soup.find_all('a'): print(x.string)

for x in soup.find_all('p'): print(x.text)

