# -*- coding: utf-8 -*-
"""Cópia de Extracao_Word.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1sP1Pkw0GQyga7aHbJN6NbURdy1s2pKw7

Neste notebook exploraremos a biblioteca "doc2text" focada em extrair o conteúdo em documentos com terminação *.doc ou *.docx
"""

# instalacao
!pip install docx2txt -q

import docx2txt
result = docx2txt.process("/content/drive/MyDrive/TopicosNLP-02_2022/Notebooks/Relatorio_Teste.docx")

print(result)

# Se o documento possuir figuras, passar mais um parâmetro com o diretório que as imagens serão armazenadas.
result = docx2txt.process("/content/drive/MyDrive/TopicosNLP-02_2022/Notebooks/Documento_Teste.docx", "/content/drive/MyDrive/TopicosNLP-02_2022/Notebooks/")