# -*- coding: utf-8 -*-
"""Tokenizacao.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1FJWK4QxfpKF1zCUC6WcyTgACCY646doR

Este notebook tem o objetivo de apresentar as técnicas de tokenização, atividade de quebrar o texto em pedaços com significado semântico.

Serão exploradas as seguintes técnicas e ferramentas:

* método “split”;
* expressões regulares
* Word Tokenizer, Sentence Tokenizer
* Treebank Tokenizer
* Tweet Tokenizer

Para exploração das técnicas, consideraremos a seguinte sentença extraída do resumo do romance Dom Quixote de La Mancha, de Miguel de Cervantes, obtido em https://www.culturagenial.com/livro-dom-quixote-de-miguel-de-cervantes/ :

"A obra narra as aventuras e desventuras de Dom Quixote, um homem de meia idade que resolveu se tornar cavaleiro andante depois de ler muitos romances de cavalaria. Providenciando cavalo e armadura, resolve lutar para provar seu amor por Dulcineia de Toboso, uma mulher imaginária. Consegue também um escudeiro, Sancho Pança, que resolve acompanhá-lo, acreditando que será recompensado."
"""

texto = ("A obra narra as aventuras e desventuras de D. Quixote, um homem de "
          "meia idade que resolveu se tornar cavaleiro andante depois de ler muitos romances "
          "de cavalaria. Providenciando cavalo e armadura, resolve lutar para provar seu amor "
          "por Dulcineia de Toboso, uma mulher imaginária. Consegue também um escudeiro, "
          "Sancho Pança, que resolve acompanhá-lo, acreditando que será recompensado...")

"""#### Utilizando o método *split*"""

tokens = texto.split()

tokens

"""Um dos problemas dessa abordagem é a pontuação, que fica vinculada a um token, prejudicando a informação dele.

#### Utilizando o expressões regulares
"""

# padrão 1
import re
regex = r'\w+'
re.findall(regex, texto)

"""Nessa solução a pontuação é descartada. Como seria a expressão se o interesse for tokenizar os sinais de pontuação também?"""

# padrão 2
regex = r'\w+|\S'
re.findall(regex, texto)

"""#### Word Tokenizer & Sentence Tokenizer
Recursos padrão da NLTK para tokenização de palavras ou sentenças. 
"""

import nltk
from nltk.tokenize import sent_tokenize, word_tokenize
nltk.download('punkt')

sent_tokenize(texto)

word_tokenize(texto)

"""#### TreeBank Tokenizer é baseado em expressões regulares. Tem mais diferenciação em textos em inglês devido ao bom tratamento nas situações de palavras em contração. Ex: I'm ; doesn't"""

from nltk.tokenize import TreebankWordTokenizer
tokenizer = TreebankWordTokenizer()
tokenizer.tokenize(texto)

"""#### Tweet Tokenizer - a manipulação de tweets é sempre trabalhosa pela quantidade de remoções de trechos sem valor que devem ser feitas no texto. Este tokenizador é especializado nisso."""

tweet1='RT @Flamengo: Mais um dia de chuva para os cariocas. Fala, @gabigol! 🥶🌧️ #VamosFlamengo https://t.co/MXQhQMhSFT'
tweet2='RT @ESPNBrasil: RT quem quer ver dancinha do Vini Jr contra o Atlético de Madrid! #BailaViniJr #LaLigaNaESPN https://t.co/P84meYNjVQ'
tweet3='RT @4evercrf__: outubro ou vai ser o mês mais feliz da minha vida ou o pior, está nas mãos do Flamengo.'

# Utilizando o word_tokenizer
word_tokenize(tweet1)

from nltk.tokenize import TweetTokenizer
tokenizer=TweetTokenizer()
tokenizer.tokenize(tweet1)

"""O TweetTokenizer reconhece questões como menção a usuários e hashtags."""

# utilizando o parâmetro 'strip_handles' retira as menções no texto 
tokenizer = TweetTokenizer(strip_handles=True)
tokenizer.tokenize(tweet1)

"""## Tokenização de tamanhos maiores que 1
Os tokens com apenas 1 palavra são chamados de unigramas. Mas ocorrem situações em que é interessante tratar as palavras vizinhas com o intuito de capturar toda a informação.

Exemplo: 'São Paulo' -> ['São', 'Paulo']

Dessa forma, quando for interessante os tokens podem ser agrupados em bigramas ou trigramas, de modo geral n-gramas.
"""

# Criação de bigramas
from nltk.util import ngrams
tokens = re.findall(regex, texto)
bigrams = list(ngrams(tokens, 2))
[" ".join(token) for token in bigrams]

# Criação de trigramas
from nltk.util import ngrams
trigrams = list(ngrams(tokens, 3))
[" ".join(token) for token in trigrams]